#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan  8 18:25:53 2021

@author: peter
"""
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path
import cancer_functions as canf
import f.general_functions as gf

import scipy.stats

df = pd.read_csv('/home/peter/data/Firefly/cancer/analysis/old_steps.csv')

df['old'] = True

df2 = pd.read_csv('/home/peter/data/Firefly/cancer/analysis/steps_20201230_sorted.csv')
df2 = df2[df2.run == 0]

df2['old'] = False

df = df.append(df2)